# base image
FROM python:3.7.0-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd


# set working directory
RUN mkdir -p /usr/src/app #optional?
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt


# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
#RUN chmod 777 /usr/src/app/entrypoint.sh # Note chmod +x does not work!!!
RUN ["chmod", "+x", "/usr/src/app/entrypoint.sh"]

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/entrypoint.sh"]
