# base image
FROM python:3.7.0-alpine

# set working directory
RUN mkdir -p /usr/src/app #optional?
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add ap
COPY . /usr/src/app

# run server
CMD python manage.py run -h 0.0.0.0
